[workspace]
members = [
    "p_1_two_sum",
    "p_2_add_two_numbers",
    "p_3_longest_substring_without_repeating_characters",
    "p_4_median_of_two_sorted_arrays",
    "p_5_longest_palindromic_substring",
    "p_6_zigzag_conversion",
    "p_7_reverse_integer",
]
resolver = "3"
