name: CI Pipeline

env:
  IMAGE_NAME: badprog_leetcode_rust_all

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} -f .devcontainer/Dockerfile .

      - name: Run linter (Clippy)
        run: docker run --rm ${{ env.IMAGE_NAME }} cargo clippy -- -D warnings

      - name: Check code formatting
        run: docker run --rm ${{ env.IMAGE_NAME }} cargo fmt --check

      - name: Run tests in container
        run: docker run --rm ${{ env.IMAGE_NAME }} cargo test --workspace

  push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64
